### PR TITLE
Add test for Parenthesized Context Mgr

### PR DESCRIPTION
**Pull request by brocla**
@BethanyG This PR has two code snippets that exercise the parenthesis feature for context managers (new in 3.10). 

I couldn't find an example directly from a student exercise, so I created this one that opens two files with a single context manager. The `open` statements are wrapped in parens, within the context manager.

The second snippet is copied from the python docs.  Even though this doesn't look like a student exercise, I like it because it succinctly goes through many variations of the parens.

### CODE REVIEW

**Comment by BethanyG** [comment]
> _The second snippet is copied from the python docs. Even though this doesn't look like a student exercise, I like it because it succinctly goes through many variations of the parens._

Completely agree that having examples of the variations is really good.  Buuut, I am a little resistant to using a long example with a bunch of `pass` statements.  Let me think on it a bit, and see if I can cobble together something that has a bit more meat on it, but isn't too tedious with the variations.

I could grab one of the concept exercise test cases, but those are rather kludgy as well.  Or maybe an example using [`Decimal.localcontext()`](https://docs.python.org/3/library/decimal.html#decimal.localcontext).

**Review by BethanyG — COMMENTED** [review]
> _The second snippet is copied from the python docs. Even though this doesn't look like a student exercise, I like it because it succinctly goes through many variations of the parens._

Completely agree that having examples of the variations is really good.  Buuut, I am a little resistant to using a long example with a bunch of `pass` statements.  Let me think on it a bit, and see if I can cobble together something that has a bit more meat on it, but isn't too tedious with the variations.

I could grab one of the concept exercise test cases, but those are rather kludgy as well.  Or maybe an example using [`Decimal.localcontext()`](https://docs.python.org/3/library/decimal.html#decimal.localcontext).

**Comment by brocla** [comment]
I just realized that I don't like my last commit. Please ignore it. I'll replace soonest.
Kevin

**Comment by brocla** [comment]
OK. Better.
I have removed the offending example and replaced it with a golden-like example. It uses the `localcontext` context manager twice, each with a different style of parens.

The example with the context manager that open two file simultaneously remains.

Kevin

**Review by BethanyG — APPROVED** [review]
Nice work, you! Thanks for putting this together.

I have a small qualm about the pandas code, since we don't have pandas installed on any of our tooling.  _However_, the code parses just fine (_it just wouldn't run if we tried evaluating it_) -- so I think we can go ahead an merge this.  😄

**Pull request merged**
